### ISSUE TITLE
Binding is broken with weak events.

### ISSUE THREAD

**Issue by grokys** [Perspex/Perspex#107]
ReactiveObject.PropertyChanged uses weak events, that don't keep alive the object that contains the event handler (for good reason). However, that means that the event handler created by Perspex.Markup.Xaml is getting disposed and so not called when the property changes.

To see this, follow these steps with the GitHubClient on the githubclient2 branch:

1. Set a breakpoint on the `subscription.Parent.PropertyChanged += ev` statement in ObservablePropertyBranch.cs
2. When the breakpoint is hit, inspect the value of `ev`, right click on the inspected value and select "Make Object ID".
3. Enter the object ID into the watch window (e.g. add a watch for `$1`)
4. Put a breakpoint on the `this.Content = vm;` line in MainWindowViewModel.cs
5. When this breakpoint is hit, see that `$1` is now null.

To fix this, the binding system should use `PerspexObject.Bind` instead of `PerspexObject.SetValue` as that way the target will have a reference to the binding which should prevent it from being GC'd.

**Comment by SuperJMN** [comment]
I'm gonna take an eye to see what's boiling there. What I don't fully understand is the WHY. I'll also take a look to how weak events work.

Maybe it's not useful, but when each Binding is created using the Create method of the PerspexPropertyBinder. It saves it's XamlBindingDefinition so you could keep a reference to it if you need to cleanup resources. I think it makes sense to retain events while the binding is there, but I don't know how to do that.

Anyways, I will try to work around PerspexObject.Bind to see what happens :)
