### ISSUE TITLE
GridSplitter

### ISSUE THREAD

**Issue by grokys** [Perspex/Perspex#121]
`GridSplitter` is currently missing the following:

- [ ] An `Orientation` property. Currently only works vertically. We shouldn't follow the WPF way of specifying the orientation because it sucks.

**Comment by danwalmsley** [comment]
On Windows it over clips, see the attached solution to repro

**Comment by danwalmsley** [comment]
<Window xmlns="https://github.com/perspex"
        xmlns:SE="clr-namespace:VEStudioX.SolutionExplorer;assembly=VEStudioX"
        Background="#2d2d30" Foreground="#C7C7C7">
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="30"/>
      <RowDefinition/>
      <RowDefinition Height="200"/>
    </Grid.RowDefinitions>

    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="250"/>
      <ColumnDefinition Width="5"/>
      <ColumnDefinition/>
    </Grid.ColumnDefinitions>

    <Menu Grid.ColumnSpan="2">
      <MenuItem Header="File">
        <MenuItem Header="New Project"/>
        <MenuItem Header="Open Project"/>
        <MenuItem Header="Save"/>
        <MenuItem Header="Save All"/>
        <MenuItem Header="Exit"/>
      </MenuItem>

      <MenuItem Header="View">
        <MenuItem Header="Console" Command="{Binding ViewToolCommand}" CommandParameter="Console"/>
        <MenuItem Header="Solution Explorer" Command="{Binding ViewToolCommand}" CommandParameter="SolutionExplorer"/>
        <MenuItem Header="Test Runner"  Command="{Binding ViewToolCommand}" CommandParameter="TestRunner"/>
        <MenuItem Header="Error List" Command="{Binding ViewToolCommand}" CommandParameter="ErrorList"/>
        <MenuItem Header="Debugging">
          <MenuItem Header="Locals" Command="{Binding ViewToolCommand}" CommandParameter="Locals"/>
          <MenuItem Header="Watch List" Command="{Binding ViewToolCommand}" CommandParameter="WatchList"/>
          <MenuItem Header="Dissasembly" Command="{Binding ViewToolCommand}" CommandParameter="Dissasembly"/>
          <MenuItem Header="Memory Viewer" Command="{Binding ViewToolCommand}" CommandParameter="Memory" />
          <MenuItem Header="Registers" Command="{Binding ViewToolCommand}" CommandParameter="Registers"/>
          <MenuItem Header="Call Stack" Command="{Binding ViewToolCommand}" CommandParameter="CallStack"/>
        </MenuItem>
      </MenuItem>

      <MenuItem Header="Tools">
        <MenuItem Header="Formatting" Command="{Binding FormatSettingsCommand}"/>
        <MenuItem Header="Options" Command="{Binding OptionsCommand}"/>
        <MenuItem Header="Packages" Command="{Binding PackagesCommand}"/>
      </MenuItem>

      <MenuItem Header="Help">
        <MenuItem Header="About" Command="{Binding AboutCommand}"/>
      </MenuItem>
    </Menu>

    
    <Grid Grid.Row="1" Grid.RowSpan="3" Background="Red" >
      
    </Grid>

    <GridSplitter Grid.Column="1" Grid.Row="1" Grid.RowSpan="2" Width="5" Background="#C7C7C7"/>


    <Grid Grid.Row="1" Grid.Column="2" Grid.RowSpan="2" RowDefinitions="*,*">
      
      
      <TextBox FontFamily="Consolas" Background="#1E1E1E" Foreground="#C7C7C7" AcceptsReturn="True" BorderThickness="0" Text="{Binding Text}"/>

      <Grid Grid.Column="1" Grid.Row="2" Background="#252526">
        <Grid.RowDefinitions>
          <RowDefinition Height="30"/>
          <RowDefinition/>
        </Grid.RowDefinitions>

        <TextBlock Margin="5,5" Text="Console"  />

        <TextBox Grid.Row="1" FontFamily="Consolas" Background="#1E1E1E" Foreground="#C7C7C7" AcceptsReturn="True" BorderThickness="0" Text="{Binding Text}"/>
      </Grid>
    </Grid>
    
  </Grid>
</Window>

**Comment by danwalmsley** [comment]
I'm having a go at this one...

**Comment by danwalmsley** [comment]
ok I tried... and didn't get very far... 

Adding an Orientation property might be difficult? It depends if it was set in a column on a grid or a row doesn't it?

Unless our grid splitter actually splits a cell into 2? then it might need a ContentLeft and ContentRight...

Perhaps that's why MSFT did it the way they did?

**Comment by ImaBrokeDude** [comment]
Well the way Gridsplitter worked is that you would place it in a row or column if it's own.

If you wanted to split a grid with a above and a below row,
you would probably have 3 rows 1 for top the middle for the splitter and one for the bottom.

The splitter would then be set to look for the rows prior and previous to the row it is in.

**Comment by grokys** [comment]
Closed https://github.com/Perspex/Perspex/pull/362
