### ISSUE TITLE
Implement loading Bitmap from Stream

### ISSUE THREAD

**Issue by kekekeks** [Perspex/Perspex#127]
- [x] Direct2D (db4a48ef7542c38862562cc818b18d4c8a3b0e31)
- [x] Cairo

**Comment by grokys** [comment]
Problems implementing this on Cairo: `ImageSurface` only supports loading png files from disk. Recommended approach is:

    image = gdk_pixbuf_new_from_file("elephant.jpg");
    gdk_cairo_set_source_pixbuf(cr, image, 0, 0);
    cairo_paint (cr);

However, `gdk_cairo_set_source_pixbuf` doesn't seem to be exposed in GtkSharp.
