### ISSUE TITLE
Intellisense support for bindings

### ISSUE THREAD

**Issue by kekekeks** [Perspex/Perspex#155]
Depends on #154 and #152. Also need to somehow obtain the type of DataContext. Possible solution is extracting one from loaded XAML. For `DataTemplates` it should be easy to extract the type from `DataType` property.

**Comment by grokys** [comment]
Migrated to https://github.com/Perspex/PerspexVS/issues/18

**Comment by cbordeman** [comment]
Use d:DataContext

**Comment by kekekeks** [comment]
The problem with the data context is that it's only viable for the root element and it's hard to actually determine the resulting type without actually evaluating the XAML. Another problem is that we could  do that reliably only for the root element which should be possible when previewer is running.

BTW, d:DataContext is currently not supported due to the lack of XAML compatibility support in Portable.Xaml. The support for that was [merged in February](https://github.com/cwensley/Portable.Xaml/pull/88), but we need to actually update our fork of OmniXAML first. The issue is tracked [here](https://github.com/AvaloniaUI/Avalonia/issues/1380).
