### ISSUE TITLE
Unable to focus second textbox if contained inside a border

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#163]
Try this xaml...

<Window xmlns="https://github.com/perspex" Background="#2d2d30" Foreground="#C7C7C7">
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="30"/>
      <RowDefinition/>
      <RowDefinition Height="200"/>
    </Grid.RowDefinitions>

    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="250"/>
      <ColumnDefinition/>
    </Grid.ColumnDefinitions>

    <Menu Grid.ColumnSpan="2">
      <MenuItem Header="File">
        <MenuItem Header="New Project"/>
        <MenuItem Header="Open Project"/>
        <MenuItem Header="Save"/>
        <MenuItem Header="Save All"/>
        <MenuItem Header="Exit"/>
      </MenuItem>

      <MenuItem Header="View">
        <MenuItem Header="Console" Command="{Binding ViewToolCommand}" CommandParameter="Console"/>
        <MenuItem Header="Solution Explorer" Command="{Binding ViewToolCommand}" CommandParameter="SolutionExplorer"/>
        <MenuItem Header="Test Runner"  Command="{Binding ViewToolCommand}" CommandParameter="TestRunner"/>
        <MenuItem Header="Error List" Command="{Binding ViewToolCommand}" CommandParameter="ErrorList"/>
        <MenuItem Header="Debugging">
          <MenuItem Header="Locals" Command="{Binding ViewToolCommand}" CommandParameter="Locals"/>
          <MenuItem Header="Watch List" Command="{Binding ViewToolCommand}" CommandParameter="WatchList"/>
          <MenuItem Header="Dissasembly" Command="{Binding ViewToolCommand}" CommandParameter="Dissasembly"/>
          <MenuItem Header="Memory Viewer" Command="{Binding ViewToolCommand}" CommandParameter="Memory" />
          <MenuItem Header="Registers" Command="{Binding ViewToolCommand}" CommandParameter="Registers"/>
          <MenuItem Header="Call Stack" Command="{Binding ViewToolCommand}" CommandParameter="CallStack"/>
        </MenuItem>
      </MenuItem>

      <MenuItem Header="Tools">
        <MenuItem Header="Formatting" Command="{Binding FormatSettingsCommand}"/>
        <MenuItem Header="Options" Command="{Binding OptionsCommand}"/>
        <MenuItem Header="Packages" Command="{Binding PackagesCommand}"/>
      </MenuItem>

      <MenuItem Header="Help">
        <MenuItem Header="About" Command="{Binding AboutCommand}"/>
      </MenuItem>
    </Menu>

    <Grid Grid.Row="1" Grid.RowSpan="3" >

    </Grid>

    <TextBox Grid.Column="1" Grid.Row="1" FontFamily="Consolas" Background="#1E1E1E" Foreground="#C7C7C7" AcceptsReturn="True" BorderThickness="0" Text="{Binding Text}"/>

    <Grid Grid.Column="1" Grid.Row="2">
      <Grid.RowDefinitions>
        <RowDefinition Height="30"/>
        <RowDefinition/>
      </Grid.RowDefinitions>

      <Border Grid.RowSpan="2" BorderBrush="#424346" BorderThickness="1"/>
      <TextBlock Margin="5,5" Text="Console"/>

      <TextBox Grid.Row="1" FontFamily="Consolas" Background="#1E1E1E" Foreground="#C7C7C7" AcceptsReturn="True" BorderThickness="0" Text="{Binding Text}"/>
    </Grid>
    
    
  </Grid>
</Window>

Second textbox can't be focused.

**Comment by grokys** [comment]
This is because the second `TextBox` is under the first `TextBox`. The `Grid` containing the second `TextBox` has `Grid.Row="2"` but there are no rows in the containing grid so everything is overlapping. This is easy to see if you open the DevTools where you can see the bounding rectangles of each control.

What is strange though is that the second `TextBox` is visible - I think this is showing up a problem with our Z-ordering that I need to investigate.

Closing, please re-open if you think I'm wrong ;)
