### ISSUE TITLE
Improve render loop.

### ISSUE THREAD

**Issue by grokys** [Perspex/Perspex#167]
I suspect our render loop can be improved. Currently to maintain the correct transform origin and clipping, we do the following:

- Push the transform
- Push the clip
- Draw the control
- Pop the transform
- Draw the children
- Pop the clip

As you can see we push and pop the transform out of order with the clip, which can't be done in cairo, so we have to hack around it.

Also, we have to pass the current translate separately from the rest of the transforms in order to make this work. I think this probably shouldn't be necessary.

The code is here:

https://github.com/Perspex/Perspex/blob/master/src/Perspex.SceneGraph/Rendering/RendererBase.cs#L79

**Comment by kekekeks** [comment]
Fixed by https://github.com/Perspex/Perspex/commit/476f853be5cdf996f7ec9b192a5f241688063151
