### ISSUE TITLE
Proposal: Readonly and Direct PerspexProperties.

### ISSUE THREAD

**Issue by grokys** [Perspex/Perspex#173]
Currently, we have no read-only `PerspexProperties` and all `PerspexProperties` are stylable, meaning they maintain a prioritized list of values and bindings that allow styles to work. However, this is overkill for many properties, such as `ItemsControl.Items` - this will never be styled and the overhead involved with current `PerspexProperties` is unnecessary.

In WPF certain properties aren't implemented as `DependencyProperties` - assumedly because the authors didn't want the overhead. However, this causes problems with bindings and change notifications among others.

This proposal is to add "Direct" `PerspexProperties` which will address read-only situations and allow a fast-path for properties that don't need to have support for styling, while retaining the advantages that `PerspexProperties` give such as metadata, binding, change notifications etc.

A "Direct" `PerspexProperty` will be implemented as follows:

        public static readonly PerspexProperty<IEnumerable> ItemsProperty =
            PerspexProperty.RegisterDirect<ItemsControl, IEnumerable>("Items", o => o.Items, (o, v) => o.Items = v);

        public IEnumerable Items
        {
            get { return _items; }
            set { SetAndRaise(ItemsProperty, ref _items, value); }
        }

As can be seen, getting the property value is now a fast path. Similarly a read-only property can be implemented as follows:

        public static readonly PerspexProperty<Rect> BoundsProperty =
            PerspexProperty.RegisterDirect<Visual, Rect>(nameof(Bounds), o => o.Bounds);

        public Rect Bounds
        {
            get { return _bounds; }
            private set { SetAndRaise(BoundsProperty, ref _bounds, value); }
        }

Things direct `PerspexProperties` will support:

- `PerspexObject.GetValue`
- `PerspexObject.SetValue` for non-readonly properties
- `PropertyChanged`
- Binding (only with `LocalValue` priority)
- `GetObservable`
- `AddOwner`
- Metadata

Things that direct `PerspexProperties` won't support:

- Validation/Coercion (although this could be done in the property setter)
- Overriding default values.
- Inherited values

**Comment by ncarrillo** [comment]
:+1 this is awesome. I'm in favor.

**Comment by ImaBrokeDude** [comment]
Will this also work for attached properties?

**Comment by grokys** [comment]
No, attached properties won't be supported as the `PerspexProperty` requires a C# property on the object itself.

**Comment by grokys** [comment]
Implemented by https://github.com/Perspex/Perspex/pull/223
