### ISSUE TITLE
Get DataTemplates working in XAML 

### ISSUE THREAD

**Issue by grokys** [Perspex/Perspex#177]
Currently `DataTemplates` are untested/not working in XAML. Make sure they work correctly for both normal items and tree items.

**Comment by grokys** [comment]
Blocked on https://github.com/SuperJMN/OmniXAML/issues/38

**Comment by grokys** [comment]
Should now be working. Needs more testing.

**Comment by SuperJMN** [comment]
We shall celebrate! DataTemplates! :D
