### ISSUE TITLE
Textbox is not accepting spaces and newlines on Windows.

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#185]

**Comment by grokys** [comment]
Newlines seem to be working as long as you set `AcceptsReturn` on the `TextBox`. You're right that space seems to be broken though!

**Comment by grokys** [comment]
@kekekeks the problem seems to be that `HandleTextInput` isn't called with spaces. Any ideas? Did this used to work?

**Comment by kekekeks** [comment]
It might got broken when I've switched to WM_CHAR.

**Comment by grokys** [comment]
I think it's this line: 

https://github.com/Perspex/Perspex/blob/master/src/Windows/Perspex.Win32/WindowImpl.cs#L302

Should be `>= 32`

**Comment by kekekeks** [comment]
Yep, surely.

**Comment by grokys** [comment]
Would it be better to use something like `char.IsControl` here? Or is that not needed?

**Comment by kekekeks** [comment]
Well, or non-printable chars are actually at the beginning of original ASCII table. Everything else is printable.

**Comment by grokys** [comment]
Does this only handle ASCII then?

**Comment by kekekeks** [comment]
First half of ASCII is a subset of unicode. All unicode chars after ASCII table are printable or should be handled as text input anyway.

**Comment by grokys** [comment]
:+1:
