### ISSUE TITLE
Allow changing of Titlebar colour on Windows

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#186]
This will allow apps to have title bar match the theme.

**Comment by grokys** [comment]
This would require client decorators as far as I know. I'm not sure that's possible on Linux or OSX so it would need to be a windows-specific functionality.

**Comment by danwalmsley** [comment]
Windows-specific would be good. Can title bar be hidden on the other platforms?

**Comment by kekekeks** [comment]
>Linux

X11 uses external decorations rendered by window manager. You can mark window as a borderless one, but it will break some nice stuff like titlebar merging with global menu when window is maximized

**Comment by danwalmsley** [comment]
I'm closing this as we can now ShowSystemDecorations = false
