### ISSUE TITLE
 Keyboard shortcuts

### ISSUE THREAD

**Issue by kekekeks** [Perspex/Perspex#200]
KeyGesture + KeyPreview should be sufficient

**Comment by kekekeks** [comment]
I'd like to have the following API:
```xml
<Panel>
  <Panel.Hotkeys>
    <Hotkey Gesture="Ctrl+Shift+B" Command="{Binding BuildCommand}"/>
  </Panel.Hotkeys>
</Panel>
```

That will be less confusing than routed commands, I think. It will also allow scoped hotkeys like in Visual Studio.

 However, that model will have some problems with defining shortcuts for menu items.

**Comment by kekekeks** [comment]
@grokys  @ncarrillo @SuperJMN I'd like to hear your thoughts about that.

**Comment by kekekeks** [comment]
Routed commands don't support:
- multiple hotkeys for the same command
- scopes
- easy reconfiguration

**Comment by kekekeks** [comment]
```xaml
<Window>
    <HotKeys>
        <HotKey Gesture="Ctrl+O" Command="{Binding OpenProjectCommand}" />
    </HotKeys>
    <MenuBar>
         <MenuItem Command="{Binding SaveProjectCommand}" HotKey="Ctrl+S" Content="Save project">
    </MenuBar>
    <StackPanel>
        <TextBox/>
        <StackPanel HotKeyScope.IsHotKeyScope="True">
            <HotKeyScope.HotKeys>
                 <HotKey Gesture="Ctrl+O" Command="{Binding OpenProjectCommand}" />
            </HotKeyScope.HotKeys>
            <Button Command="{Binding SaveProjectCommand}" HotKey="Ctrl+S" Content="Save file"/>
            <TextBox/>
        </StackPanel>
    </StackPanel>
</Window>

```

Controls can be hotkey scopes, which have the list of registered hotkeys. Certain controls that have a `Command` associated with them can have a hotkey, that they will register in the nearest hotkey scope. In example above textboxes are in different hotkey scopes so hotkeys have different meaning. Key gestures are also completely decoupled from command implementations.

**Comment by grokys** [comment]
If the first `TextBox` is focused and the user presses `Ctrl+S`, would `SaveProjectCommand` get called? What would the route be that would result in it being called?

**Comment by kekekeks** [comment]
Somewhere in input management code it will walk through widget hierarchy from focused widgets through it's parents and check if any of them have a KeyGesture associated with the current combination. It match is found, the command is called. That should happen before passing KeyUp/KeyDown events to the focused control.

**Comment by ImaBrokeDude** [comment]
How could we get this to work if we want to register a global hotkey? (Allows hotkey to be invoked when window is not active)

**Comment by kekekeks** [comment]
Global hotkeys are completely unrelated to this

**Comment by grokys** [comment]
Yeah, makes sense. Only remaining question for me is whether unhandled keys get passed to the parent scope. I assume they do? 

Anyway, it's a :+1: from me.

**Comment by kekekeks** [comment]
Yep, they should be passed to parent scope.

**Comment by kekekeks** [comment]
I have no means to subscribe to visual root (can be done by storing visual root in direct perspex property, but it depends on #173). Logical parent is unreliable (ContentControl doesn't set the logical parent for some reason). So, by now I've added support for KeyBindings and HotKey feature moves to beta1

**Comment by kekekeks** [comment]
Everything but scopes should be working now.

**Comment by HossamElwahsh** [comment]
> How could we get this to work if we want to register a global hotkey? (Allows hotkey to be invoked when window is not active)

Got any solution yet for that after 7 years?

I can't access winProc from Avalonia as it's private protected in the API, found no solution for global hotkeys and it's critical to my project.

**Comment by jp2masa** [comment]
This should work for Windows: https://github.com/AvaloniaUI/Avalonia/discussions/8823#discussioncomment-3473014.

**Comment by MrDoe** [comment]
> This should work for Windows: [#8823 (reply in thread)](https://github.com/AvaloniaUI/Avalonia/discussions/8823#discussioncomment-3473014).

This doesn't work with Avalonia v11.1.3 and .NET 8.
