### ISSUE TITLE
InvalidOperationException in ItemContainerGenerator

### ISSUE THREAD

**Issue by ncarrillo** [Perspex/Perspex#212]
{"Container already created."}
   
{Void AddContainers(Int32, System.Collections.Generic.IList`1[Perspex.Controls.IControl])}
    at Perspex.Controls.Generators.ItemContainerGenerator.AddContainers(Int32 index, IList`1 container) in Perspex\src\Perspex.Controls\Generators\ItemContainerGenerator.cs:line 168

Can be triggered by using keyboard navigation to go through the pages in the Gallery app quickly.

**Comment by grokys** [comment]
This is actually quite complex - it's happening because the page transition is trying to start a new transition before the old transition has finished. We need a way to cancel transitions.
