### ISSUE TITLE
Invalid Bitmap Width/Height results in incorrect DrawImage rendering

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#218]
![perspexbitmap](https://cloud.githubusercontent.com/assets/2297442/10131034/7dcdce26-65cd-11e5-9ccf-52ac3d05f283.png)

**Comment by grokys** [comment]
Could you attach the image you're seeing this issue with?

**Comment by wieslawsoltes** [comment]
http://imgs.xkcd.com/comics/iso_8601.png
