### ISSUE TITLE
SaveFileDialog does not append file extension in ShowAsync resturn value

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#229]
If user does not provide file name extension, the return value should be appended with file extension using the extension provided in selected FileDialogFilter.

**Comment by tshcherban** [comment]
Should the return value be appended with first extension, if filter has more than 1 item?

**Comment by wieslawsoltes** [comment]
For example:

``` C#
var dlg = new SaveFileDialog();
dlg.Filters.Add(new FileDialogFilter() { Name = "Pdf", Extensions = { "pdf" } });
dlg.Filters.Add(new FileDialogFilter() { Name = "Dxf", Extensions = { "dxf" } });
dlg.Filters.Add(new FileDialogFilter() { Name = "All", Extensions = { "*" } });
dlg.InitialFileName = _context.Editor.Project.Name;
var result = await dlg.ShowAsync(this);
if (result != null)
{
    ...
}
```

If user selects the `"Dxf"` filter, then `result` file name should have the `.dxf` file extension appended (off course if not provided by user).
