### ISSUE TITLE
Wierd Offset between where stuff is rendered and where the HitTest thinks controls are:

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#245]
![image](https://cloud.githubusercontent.com/assets/4672627/10280610/496e9108-6b66-11e5-960f-4aa5fbb89f53.png)
```
<UserControl xmlns="https://github.com/perspex" xmlns:Packages="clr-namespace:AvalonStudio.Models.PackageManager;assembly=AvalonStudio.Models">
  <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="150"/>
      <ColumnDefinition/>
    </Grid.ColumnDefinitions>

    <ListBox Items="{Binding AvailablePackages}" SelectedItem="{Binding SelectedPackage}" IsEnabled="{Binding EnableInterface}">
      <ListBox.DataTemplates>
        <DataTemplate DataType="Packages:Package">
          <TextBlock Text="{Binding Name}"/>
        </DataTemplate>
      </ListBox.DataTemplates>
    </ListBox>

    <Grid Grid.Column="1">
      <Grid.RowDefinitions>
        <RowDefinition Height="30"/>
        <RowDefinition Height="30"/>
        <RowDefinition/>
        <RowDefinition Height="*"/>
      </Grid.RowDefinitions>
      <Grid.ColumnDefinitions>
        <ColumnDefinition Width="80"/>
        <ColumnDefinition/>
      </Grid.ColumnDefinitions>

      <TextBlock Text="Name" HorizontalAlignment="Right"/>
      <TextBlock Grid.Column="1" Text="{Binding SelectedPackage.Name}"/>

      <TextBlock Grid.Row="1" Text="Description" HorizontalAlignment="Right"/>
      <TextBlock Grid.Row="2" Grid.Column="1" Text="{Binding SelectedPackage.Description}"/>

      <TextBlock Grid.Row="3" Grid.Column="1" Text="{Binding Status}"/>
      <Button Grid.Row="3" Grid.Column="1" HorizontalAlignment="Center" VerticalAlignment="Center" Content="{Binding ButtonText}" Command="{Binding InstallCommand}"/>
    </Grid>
  </Grid>
</UserControl>
```

It is resulting in me not being able to select items in the ListBox... DevTools thinks the whole grid is in a different location to where rendered on the screen.

Appears disabled but I think that's a styling issue...

To repro.. you can use above code, or clone this commit:
https://github.com/VitalElement/AvalonStudio/commit/e845a83abf5965d319183fdc284879a0c9e9b6bc

Compile and run, then click Tools->Packages

**Comment by grokys** [comment]
I can't get AvalonStudio at the specified commit to compile as ModalDialog is missing, and if I paste the XAML into the Perspex test application removing the missing stuff, it seems to work.

Could you confirm this is still a problem and give me a commit that compiles?

**Comment by danwalmsley** [comment]
Problem identified... Since the plugin does not have a template for usercontrol I had changed the Xaml to UserControl, but the code behind Id left inheriting from Window...

So its actually a Window inside that grid causing the issue. Can we perhaps get an exception of this happens, I assume a Window inside a Grid is illegal?
