### ISSUE TITLE
Implement Generic Data Template

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#246]
In wpf you could have a DataTemplate without a target type set... here is an example...

```
 <ListBox.ItemTemplate>
                <DataTemplate>
                    <Label Content="{Binding Name}"/>
                </DataTemplate>
</ListBox.ItemTemplate>
```

In Perspex I tried something similar...

```
<ListBox Items="{Binding AvailablePackages}" SelectedItem="{Binding SelectedPackage}" IsEnabled="{Binding EnableInterface}">
      <ListBox.DataTemplates>
        <DataTemplate>
          <TextBlock Text="Test"/>
        </DataTemplate>
      </ListBox.DataTemplates>
    </ListBox>
```

But get the exception 
```
"An exception of type 'System.InvalidOperationException' occurred in Perspex.Markup.Xaml.dll but was not handled in user code

Additional information: DataTemplate must have a DataType."
```

**Comment by danwalmsley** [comment]
Seems to be in DataTemplate.cs and TreeDataTemplate.cs....

If DataType == null then it should just try to bind to those properties on whatever object it is regardless of type...

**Comment by grokys** [comment]
No, a `DataTemplate` in the `DataTemplates` collection always needs to have a `DataType`, just as WPF `DataTemplates` in the `Resources` section need to.

The difference is that WPF has `ItemsControl.ItemTemplate` which Perspex doesn't have yet.

However, where does the need for a `DataTemplate` that is applied regardless of underlying type come from? Usually all items in the list that you are binding to have the same type, or inherit from the same type.

**Comment by danwalmsley** [comment]
ok agreed... will close issue
