### ISSUE TITLE
Unable to Parse Binding Mode=TwoWay

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#253]
ListBox Items="{Binding AvailablePackages}" SelectedItem="{Binding SelectedPackage, Mode=TwoWay}" IsEnabled="{Binding EnableInterface}"

Is causing exception:
System.ArgumentException: 'expression' may not be empty.

I think its related to recent fixes on expression parsing.

**Comment by danwalmsley** [comment]
This works if I use:
```
SelectedItem="{Binding Path=SelectedPackage, Mode=TwoWay}"
```

**Comment by grokys** [comment]
This seems to be a bug in OmniXAML where binding extensions aren't being correctly parsed when a property has a dependency on another property.

**Comment by danwalmsley** [comment]
Agreed: filed a bug with OmniXaml.

https://github.com/SuperJMN/OmniXAML/issues/45
