### ISSUE TITLE
Invalid mouse button mapping on Linux/Gtx for Control in PointerPressed event args

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#263]
Invalid mouse button mapping on Linux/Gtx for Control in PointerPressed event args:
* Left button is Right
* Right button is Middle

Middle button is ok.

**Comment by wieslawsoltes** [comment]
Tested the fix, found some issues:
- The `PointerPressed` Left mouse button event is OK.
- On the `PointerReleased` Left mouse button event you get Right mouse button instead.
- On the `PointerPressed` Right mouse button event you get Middle mouse button instead.
- On the `PointerReleased` Right mouse button event you get Middle mouse button instead.
- On the `PointerPressed` Middle mouse button event  you get Right mouse button instead.
- The `PointerReleased` Middle mouse button event is OK.

**Comment by kekekeks** [comment]
Oh, I haven't fixed the second handler, sorry

**Comment by kekekeks** [comment]
Actually, I got it all wrong
