### ISSUE TITLE
Accessing list or collection of containers using ItemsContainerGenerater

### ISSUE THREAD

**Issue by ImaBrokeDude** [Perspex/Perspex#275]
With WPF I could iterate through containers using the following:

`itemsControl.ItemContainerGenerator.Items.Count`

However I do not see a way to iterate with our current implementation.

Maybe I am just missing something?

**Comment by grokys** [comment]
Does `IItemContainerGenerator.Containers` not work?

I renamed it from that in WPF because `Items` is ambiguous between the items and the containers.

**Comment by ImaBrokeDude** [comment]
Actually it appears with my build `IItemContainerGenerator.Containers` is not available.

**Comment by ImaBrokeDude** [comment]
`IItemContainerGenerator.Containers` Was added in Alpha2. This resolved my question.
