### ISSUE TITLE
Add support for TabItem headers wrapping in TabControl

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#289]
![1](https://cloud.githubusercontent.com/assets/2297442/10716060/bf5025b0-7b2b-11e5-91a8-2e46267cc9e5.PNG)

![2](https://cloud.githubusercontent.com/assets/2297442/10716059/bf39a344-7b2b-11e5-90bb-f25bb3eb373e.PNG)

**Comment by susloparovdenis** [comment]
I've almost done a **WrapPanel**. I am going to pull requst soon.
But  I can't figure out how to change ItemsPanel for TabStrip in xaml. There is no such thing as ItemsPanelTemplate.

**Comment by grokys** [comment]
There certainly is: https://github.com/Perspex/Perspex/blob/master/src/Perspex.Controls/ItemsControl.cs#L100

Or is that not working? Maybe we should add the "Template" postfix to make it the same as in WPF.
