### ISSUE TITLE
MenuItem HotKey command is not executed

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#296]
```XAML
<MenuItem Header="_New" HotKey="Ctrl+N" Command="{Binding Path=Commands.NewCommand}"/>
```

**Comment by grokys** [comment]
The hotkey support needs to initialize itself on `Control.AttachedToLogicalTree` (which has just been added) instead of when it's attached to the visual tree. cc: @kekekeks

**Comment by wieslawsoltes** [comment]
Yes, its fixed.
