### ISSUE TITLE
Add QuadTo method to StreamGeometryContext

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#305]
`StreamGeometryContext` is missing `QuadTo` method available in `IStreamGeometryContextImpl` 

https://github.com/Perspex/Perspex/blob/01562bd98c20fec2608fcdc70c5e0cbed5a81c8b/src/Perspex.SceneGraph/Media/StreamGeometryContext.cs#L18

https://github.com/Perspex/Perspex/blob/4907e551cdcba25d3ecb5162e08af0d3817b31f5/src/Perspex.SceneGraph/Platform/IStreamGeometryContextImpl.cs#L46

**Comment by grokys** [comment]
In WPF, this appears to be called `PolyQuadraticBezierTo` - should we use that naming?
