### ISSUE TITLE
Direct2D LineCap is not set for Pen

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#313]
Direct2D LineCap is not set for Pen
![caps_d2d](https://cloud.githubusercontent.com/assets/2297442/11068604/61c3d85c-87d2-11e5-8280-f9f1401e5e73.PNG)

Skia version with proper LineCap's
![caps_skia](https://cloud.githubusercontent.com/assets/2297442/11068606/64f81d3a-87d2-11e5-8c7d-5f3a10c03e31.PNG)

**Comment by susloparovdenis** [comment]
Oh my gosh. Why are there so many mentions of fix commit? I messed up with rebasing a lot, in history and the pull requst everything looks nice though. Guys, tell me is it OK? :)
