### ISSUE TITLE
Test project: Xaml file not found

### ISSUE THREAD

**Issue by KeKl** [Perspex/Perspex#319]
Hi,

I tried to create a test project:
https://github.com/KeKl/PerspexTest

I marked the .paml files as EmbeddedResource but I get a FileNotFoundException.
Additional information: The type "{:Application} cannot be found"

I looked into the samples in the repo, but I dont see any differences. I use the nuget version alpha 2.

What am I doing wrong?

Regards,
Kevin

**Comment by kekekeks** [comment]
Try to use application template from our VS extension

**Comment by KeKl** [comment]
I moved the paml and paml.cs window files into the exe library. Thats working now.

But for the App.paml and App.paml.cs I still get the Exception: 
OmniXaml.XamlParseException: The type "{:Application} cannot be found"

**Comment by grokys** [comment]
Are you still on alpha 2? I don't think having XAML for Application was supported back then.

We really need to release alpha 3 - we've done so much work since alpha 2...

**Comment by KeKl** [comment]
Ok, then I will wait for the new release. 
Having the UI things (xaml) in another dll is working?

**Comment by grokys** [comment]
Yep, that shouldn't be a problem

**Comment by KeKl** [comment]
I will wait for the nexr release. Thanks
