### ISSUE TITLE
Nuget Package - Not providing Perspex.Desktop / Perspex.Direct2d assemblies

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#326]
Recently tried to update my nugget package, but application just crashes trying to unable to reference assembly Perspex.Direct2D.

**Comment by grokys** [comment]
You now need to add the Perspex.Desktop NuGet package to your project. Are you still unable to do this?

**Comment by danwalmsley** [comment]
yes, Perspex.Desktop throws exceptions when package manager is trying to install
```
Install failed. Rolling back...
Package 'SharpDX 2.6.3' does not exist in project 'AvalonStudio'
Package 'SharpDX 2.6.3' does not exist in folder 'C:\development\repos\avalonstudio\AvalonStudio\packages'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

**Comment by grokys** [comment]
Try manually removing the package from packages.config and then re-adding it.

**Comment by danwalmsley** [comment]
@grokys solution was to delete my project file and start again... putting it down to moving between various builds that must have broken something along the way.
