### ISSUE TITLE
Exception: Cannot find a property named "Row" in the type Perspex.Controls.Shapes.Rectangle

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#344]
Code to reproduce the issue
```XAML
<Rectangle Width="100" Height="100" Fill="Red">
    <Grid.Row>1</Grid.Row>
</Rectangle>
```

Reported also to OmniXaml https://github.com/SuperJMN/OmniXAML/issues/65

**Comment by grokys** [comment]
@wieslawsoltes is this fixed by omnixaml update?

**Comment by wieslawsoltes** [comment]
Its fixed in OmniXAML

**Comment by wieslawsoltes** [comment]
I should add, that fix is working for this case, but there are some other associated issues, more details are included in reported OmniXAML issue.
