### ISSUE TITLE
AttachedProperties

### ISSUE THREAD

**Issue by KeKl** [Perspex/Perspex#345]
Hi,

I try to create a attached property:

C#:

        public static readonly PerspexProperty<bool> AutoWireViewModelProperty = 
                PerspexProperty.RegisterAttached<IControl, bool>("AutoWireViewModel", typeof(ViewModelLocator));

        public static bool GetAutoWireViewModel(IControl obj)
        {
            return obj.GetValue(AutoWireViewModelProperty);
        }

        public static void SetAutoWireViewModel(IControl obj, bool value)
        {
            obj.SetValue(AutoWireViewModelProperty, value);
        }

Xaml:

        <Window xmlns="https://github.com/perspex"
                xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Perspex.Desktop"
                prism:ViewModelLocator.AutoWireViewModel="true">
  
          <TextBlock FontSize="25" FontWeight="Bold" Text="{Binding TestText}" />

        </Window>

I get a error loading XAML: System.ArgumentException: Property 'AutoWireViewModel not registered on 'HelloWorld.Views.MainWindow.

How to define a attached property?

Regards

**Comment by KeKl** [comment]
Ok, the IControl has to be a Control.

**Comment by grokys** [comment]
Hi KiKI, yes sorry, that's a limitation that I want to lift.
