### ISSUE TITLE
DockPanel Docking not completly working

### ISSUE THREAD

**Issue by KeKl** [Perspex/Perspex#348]
Hi,

following Code produces the attached window. When I put the textbox below the button, it will be rendered correct.

    <DockPanel LastChildFill="true">

    <Menu DockPanel.Dock="Top">
      <MenuItem Header="File">
        <MenuItem Header="New Window" />
        <Separator />
        <MenuItem Header="Exit" Command="{Binding ExitCommand}" />
      </MenuItem>
    </Menu>
    
    <TextBox DockPanel.Dock="Top" Height="250" FontSize="25" Text="{Binding TestText}" />
    
    <Button DockPanel.Dock="Bottom" Height="25" Content="ChangeText" Command="{Binding ChangeTextCommand}" />
      </DockPanel>

![dock](https://cloud.githubusercontent.com/assets/8339361/11614428/c0792170-9c42-11e5-850f-69eccefe4d8f.PNG)

**Comment by grokys** [comment]
@SuperJMN implemented `DockPanel`: any ideas?

**Comment by SuperJMN** [comment]
I'll check it!
