### ISSUE TITLE
Text is blurred - Perspex 0.2.0-alpha3

### ISSUE THREAD

**Issue by Sergey-Terekhin** [Perspex/Perspex#355]
Text in the runtime looks blurred, but in the designer everything is Ok (I understand that designer is drawn by WPF with TextOptions.TextFormattingMode set to "DIsplay" value). 

Do you have plans to implement some sharpening options like SnapToDevicePixels, TextOptions.TextFormattingMode etc.?

**Comment by kekekeks** [comment]
>I understand that designer is drawn by WPF with TextOptions.TextFormattingMode set to "DIsplay" value

Designer is drawn using the same rendering backend as in runtime, basically it's native win32 window  drawn by Perspex and embedded in visual studio, so

**Comment by Sergey-Terekhin** [comment]
Designer:
![Designer](http://imgur.com/lCySNPY)

Runtime:
![Runtime](http://imgur.com/3BMWE1A)

**Comment by kekekeks** [comment]
It seems that you are using system scaling. Perspex currently isn't DPI aware on desktop systems, so text is scaled by the DWM after its rendered.

**Comment by Sergey-Terekhin** [comment]
Yes, you're right
