### ISSUE TITLE
Bug with WrapPanel in designer

### ISSUE THREAD

**Issue by Sergey-Terekhin** [Perspex/Perspex#357]
WrapPanel in the designer does not wrap content (see images below)
Runtime:
![WrapPanel in Runtime](http://i.imgur.com/abC4W9q.png?1)

Designer:
![WrapPanel in Designer](http://i.imgur.com/wottkjX.png?1)

**Comment by kekekeks** [comment]
Your links are giving me "Not Found", please upload screenshots to some image hosting service like imgur.com

**Comment by Sergey-Terekhin** [comment]
Updated

**Comment by grokys** [comment]
Migrated to https://github.com/Perspex/PerspexVS/issues/19
