### ISSUE TITLE
Menu Control - MenuItems - Not inheriting foreground and background

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#364]
The top level menu inherits background and foreground colours.

Also not obeying explicitly set colours either.

**Comment by grokys** [comment]
`Background` is not an inherited property, so one would expect the child menus not to inherit it. The same behavior occurs in WPF.

Also, with the latest changes, `MenuItem`s now obey explicitly set colors, so closing.

**Comment by danwalmsley** [comment]
```
<Menu Grid.ColumnSpan="2" Background="Red">
    <MenuItem Header="File">
      <MenuItem Header="New Project"/>
      <MenuItem Header="Open Project" Command="{Binding LoadProjectCommand}"/>
      <MenuItem Header="Save" HotKey="Ctrl+S" Command="{Binding SaveCommand}" />
      <MenuItem Header="Save All"/>
      <MenuItem Header="Exit"/>
    </MenuItem>
```

**Comment by danwalmsley** [comment]
![image](https://cloud.githubusercontent.com/assets/4672627/11873495/c7b12bca-a4d2-11e5-95fd-e644ae90b271.png)

**Comment by danwalmsley** [comment]
Shouldn't the menu items be red... I don't want to have to specify background colour each time?

**Comment by grokys** [comment]
Try the same on WPF - it's expected behavior. There will be a way to set this more easily with an upcoming change though.

**Comment by grokys** [comment]
In the meantime, you can add a style to the menu to set `MenuItem`s Background color.

**Comment by danwalmsley** [comment]
![image](https://cloud.githubusercontent.com/assets/4672627/11873711/ef6ec4aa-a4d3-11e5-947c-f447ff3fad14.png)

**Comment by danwalmsley** [comment]
```
 <Menu Grid.ColumnSpan="2" Background="Red">

    <Menu.Styles>
      <Style Selector="MenuItem">
        <Setter Property="Background" Value="Red" />
      </Style>
    </Menu.Styles>
    <MenuItem Header="File">
      <MenuItem Header="New Project"/>
      <MenuItem Header="Open Project" Command="{Binding LoadProjectCommand}"/>
      <MenuItem Header="Save" HotKey="Ctrl+S" Command="{Binding SaveCommand}" />
      <MenuItem Header="Save All"/>
      <MenuItem Header="Exit"/>
    </MenuItem>
```

**Comment by danwalmsley** [comment]
Any way to get the entire sub-menu red?
