### ISSUE TITLE
Custom Style for Template child control is not applied correctly

### ISSUE THREAD

**Issue by donandren** [Perspex/Perspex#368]
example Style - Expander.paml

if in DefaultTheme.paml style Expander.paml is included before ToggleButton.paml:
```
  <StyleInclude Source="resource://application/Perspex.Themes.Default/Perspex.Themes.Default.Expander.paml"/>
  <StyleInclude Source="resource://application/Perspex.Themes.Default/Perspex.Themes.Default.ToggleButton.paml"/>
```

For the toggle button in the expander header, default style for ToggleButton is used not the one specified in Expander.paml.

**Comment by grokys** [comment]
This is expected behavior I think - later styles have precedence of earlier styles, and the default ToggleButton style will apply to *all* ToggleButtons.
