### ISSUE TITLE
TreeView Performance

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#369]
Tree View with large datasets, slows my entire application, even then the TreeViews state is not changing, it will slow the entire render loop...

Collapsing all items gets the speed up again.

Perhaps data virtualization needs implementing.

https://github.com/VitalElement/AvalonStudio/commit/c385dfb9971979909885e4e42b765a227ba5e3b1 will repro, open the Sample Project in AvalonStudio once it opens...

open a text file, then try and move the caret by holding down button, it will be slow,

then collapse the treeview to top level, and try moving caret again.... it will be fast.

**Comment by grokys** [comment]
Actually I think the performance for this case can be achieved quite simply - just don't render controls that are outside the bounds of a parent with `ClipToBounds = true`.

**Comment by danwalmsley** [comment]
Ok thanks will give it a go later and report back

**Comment by danwalmsley** [comment]
This didn't seem to make any difference, perhaps its not rendering, and something is still processing all the items in the treeview?

**Comment by danwalmsley** [comment]
Ran the profiler without clip to bounds...
![image](https://cloud.githubusercontent.com/assets/4672627/11913555/7d75a494-a65f-11e5-88b8-50b76bfcd8b7.png)

must be in the rendering

**Comment by danwalmsley** [comment]
and with clip to bounds...
![image](https://cloud.githubusercontent.com/assets/4672627/11913563/e992bb08-a65f-11e5-9d7c-6e3af8347956.png)

**Comment by danwalmsley** [comment]
then when collapsed there is a huge reduction in cpu usage
![image](https://cloud.githubusercontent.com/assets/4672627/11913570/39dc791e-a660-11e5-9d70-2ec2df41502d.png)

**Comment by grokys** [comment]
Sorry, I don't understand... I've not changed anything yet so the ClipToBounds optimization isn't there yet.

**Comment by danwalmsley** [comment]
ah sorry I thought you meant that ClipToBounds was ready and you were talking about virtualization

**Comment by danwalmsley** [comment]
Clip to bounds has worked wonders, thank you.
