### ISSUE TITLE
IScrollable - Doesnt get correct measurements on component load

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#370]
https://github.com/VitalElement/AvalonStudio/commit/c385dfb9971979909885e4e42b765a227ba5e3b1

Above commit will repro the problem...

Open the sample project in AvalonStudio, then select the first file in solution explorer.

Now look at the vertical scrollbar... and take note of the thumb size.

Now resize the entire application a little, and take note of the thumb size.

You will size that initially some miscalculation has occurred. I checked my code and could see no reason for this to happen to it could be a bug in the Perspex implementation.

**Comment by grokys** [comment]
Is this still a problem? I just checked and couldn't get it to happen with master (commit you posted doesn't compile with latest perspex)

**Comment by danwalmsley** [comment]
This seems to have been resolved now.
