### ISSUE TITLE
Remove dependency on Serilog

### ISSUE THREAD

**Issue by dealproc** [Perspex/Perspex#388]
Folks - 

Cool framework, but is a bit rough that there's a direct dependency on a logging framework (it's a bit opinionated).  Serilog is pretty slick, and hat's off to nick for building it, but I'm not sure it's the way to go.

Any possibility of investigating something like: https://github.com/damianh/LibLog instead, whereas your code isn't linked to a specific logging framework?

Just my $0.02 on this.

**Comment by grokys** [comment]
Hi @dealproc, yes I'm aware that the dependency on Serilog isn't ideal. However, at this stage in development I didn't want to concern myself with logging; I just wanted something to *log stuff*. LibLog or something similar looks like it may be a good solution in the future, but for the moment I'd prefer to keep things simple and work on the important parts while maintaining logging. Leaving this issue open because it's something we definitely need to revisit later.

**Comment by dealproc** [comment]
:+1: Cool.  Yea, the basic concept is that you'd drop the source in, and you just redirect to the LibLog libs:

`static ILog _log = LogProvider.For<{yourClassImplementation}>();`

and the rest is the same as you have now with Serilog.

Pending i can get into VS2015 in the next 2-3 weeks, would you be interested in a PR for this?  Would give me a chance to read through the code and get some better understanding of the framework.

**Comment by grokys** [comment]
Unsure, to be honest I'm happy to just keep things as they are for now for simplicity's sake at least until we get into beta. But if it's as simple as you say it is, then maybe. How does this affect the loggin configuration on the client?

**Comment by grokys** [comment]
Actually, I've changed my mind here. Yes, if you could submit a PR that would be good.

**Comment by dealproc** [comment]
It doesn't affect anything on the client, IIRC, as the LibLog system dynamically resolves which logging framework(s) you use.  If you know what your tags are to do appropriate log filtering with Serilog, NLog, log4net, etc., you setup your sinks with the appropriate filters and go to town on it.

Now my only issue is going to be that I need to learn how to use the different contexts that you are using, first with Serilog, and then to figure out how to do the same with LibLog.

**Comment by arkadiuszwojcik** [comment]
Isn't better to use Microsoft.Extensions.Logging.Abstractions (from .net core) instead of LibLog ?  Eventually that will be official logging abstraction framework for .net I guess.

**Comment by dealproc** [comment]
I think @grokys needs to evaluate the licensing between the two and determine if the microsoft licensing is permissible enough for this framework, and whether or not it meets his end goals in that regard.  Perspex is released as MIT Licensed, as well as LibLog (not explicitly stated, but the license says use it at your own risk, etc.)  Microsoft's lib is saying Apache-2 licensing, which i know is more restricted to a point, but am unsure how deep the restrictions go.

Any advice on this @arkadiuszwojcik ?

**Comment by grokys** [comment]
I don't believe there's any problem using an apache licensed project in a MIT licensed one.

**Comment by arkadiuszwojcik** [comment]
I also think there shouldn't be any problems until we just use library. Most Apache-2 licensing restrictions apply to scenarios where source code of such library is being modified.

**Comment by dealproc** [comment]
Cool!  Next questions:

Is the microsoft licensed library going to give you the same contextual features you presently have within Serilog, or are you limited to access?  I've not looked at Microsoft's abstraction, so we need to research this out.

What does the xplat support look like for Microsoft's implementation?

**Comment by grokys** [comment]
Serilog dependency has now been moved to the `Perspex.Logging.Serilog` assembly. See docs at https://github.com/Perspex/Perspex/blob/master/docs/spec/logging.md for more info.
