### ISSUE TITLE
Window WindowState not working properly on Win32 platform

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#436]
**Normal**
 ```XAML
<Window xmlns="https://github.com/perspex"
        Title="MainWindow" Height="600" Width="600" WindowState="Normal">
</Window>
```
![windowstate-normal](https://cloud.githubusercontent.com/assets/2297442/13151856/60bf0bdc-d66c-11e5-9f4e-e565a03db903.PNG)

**Minimized**
 ```XAML
<Window xmlns="https://github.com/perspex"
        Title="MainWindow" Height="600" Width="600" WindowState="Minimized">
</Window>
```
![windowstate-minimized](https://cloud.githubusercontent.com/assets/2297442/13151867/6ea5a5c6-d66c-11e5-8e8e-1f9ab41c15b5.PNG)

**Maximized**
 ```XAML
<Window xmlns="https://github.com/perspex"
        Title="MainWindow" Height="600" Width="600" WindowState="Maximized">
</Window>
```
![windowstate-maximized](https://cloud.githubusercontent.com/assets/2297442/13151875/73e22604-d66c-11e5-92e4-b1b7c932895f.PNG)

**Not set at all**
 ```XAML
<Window xmlns="https://github.com/perspex"
        Title="MainWindow" Height="600" Width="600">
</Window>
```
![windowstate-is_not_set](https://cloud.githubusercontent.com/assets/2297442/13151898/937aea46-d66c-11e5-87fd-31792cec3343.PNG)

**Comment by grokys** [comment]
Thanks @wieslawsoltes - you're a bug-finding MACHINE ;)
