### ISSUE TITLE
implement application.exit

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#443]

**Comment by grokys** [comment]
To implement this, we'll need to keep a track of opened `Window` objects and close them when `Application.Exit` is called.

**Comment by jkoritzinsky** [comment]
Is this for implementing the WPF `Application.Exit` event or the Windows Forms `Application.Exit` method?

**Comment by Seeker1437** [comment]
I would so both really aka an event and the actual method.

**Comment by grokys** [comment]
This is for implementing the Perspex `Application.Exit` :)

**Comment by jkoritzinsky** [comment]
@grokys I know, I was just wondering which one this was supposed to be an analog for, since this project is like "next WPF" but your comment matched the description of the Windows Forms `Application.Exit`.

**Comment by Seeker1437** [comment]
Ooooh right because it's `Application.Current.Shutdown()` for WPF

**Comment by jkoritzinsky** [comment]
I'm working on this now on the `application.exit` branch on my fork.

**Comment by jvanlangen** [comment]
Not able to find the Application.Exit method.. Still not implemented?

**Comment by kekekeks** [comment]
See https://docs.avaloniaui.net/docs/getting-started/application-lifetimes
