### ISSUE TITLE
Wierd ScrollViewer behaviour in AvalonStudio

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#444]
For some reason when my intellisense control comes up, the ScrollViewer tries to scroll my TextView control down by an illegal value...

This did not happen before... you can reproduce it by performing the following steps:

Clone AvalonStudio, current master will do.

change LineNumberMargin.cs line 26 to:
```
if (textView.TextDocument != null && textView.VisualLines.Count > 0)
```
otherwise the error will crash the whole app.

Then run AS.

Do File->New Project

Select STM32 Project

click ok.

In Solution Explorer, click main.cpp

then add lots of new lines above int main (void){}

then start typing the word static.. on the letter s, intellisense will pop up, but when you press T it will cause the scrollviewer to scroll down! Where is this coming from, this didn't happen with older builds (but a long time since I tested this.)

**Comment by danwalmsley** [comment]
Ok it looks like perhaps ScrollContentPresenter.cs is sending setting offset on the wrong control perhaps.
I can get it not to crash but not selecting items in the intellisense (Listbox) control.

**Comment by grokys** [comment]
I've just tried reproducing with Avalon Studio master, but when i do "File -> New Project" the dialog is empty.

**Comment by danwalmsley** [comment]
ok as discussed cause determined as bringing control into view, including invisible margin.
