### ISSUE TITLE
DPI support problematic

### ISSUE THREAD

**Issue by superlloyd** [Perspex/Perspex#445]
Just downloaded the github repo, running the test app.
My mouse click are off, I need to click outside button / text to select them!

The problem get worse towards the bottom right of the window!

**Comment by grokys** [comment]
Thanks for the report @superlloyd - what OS are you using and what is your current DPI scaling?

**Comment by grokys** [comment]
Actually, when running at 125% here, button clicks are ok, but selecting text is off. I will investigate.

**Comment by superlloyd** [comment]
Windows 10. 
I set a custom DPI which I can't remember but the display panel seems to say I set it at 225% (which I doubt...) fact is I set a custom scaling one day to be as wysiwyg as possible... it was more like 114% IIRC

**Comment by superlloyd** [comment]
Nice you can experience it!
Good luck fixing it! ;)

**Comment by grokys** [comment]
`DropDown` now broken on high-dpi.

**Comment by grokys** [comment]
Still not fixed. ARGH.

**Comment by grokys** [comment]
Should hopefully be fixed now.

**Comment by superlloyd** [comment]
As they say, works on my computer! (now) :)
