### ISSUE TITLE
ListBox  SelectedItem sometimes getting ignored

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#454]
When setting SelectedItem in ViewModel the event seems to get ignored in somecases....

To repro clone: 
https://github.com/VitalElement/AvalonStudio/commit/395609ce7d51ef5c8cd558f2483f6c782f13fc7a

Then clean solution, build solution, then compile and debug to run Avalon studio:
, then do File->New Project
the STM32 Project.

Then open main.cpp

Ok the issue appears when using intellisense.

so open up the main function, and type the letter m, this should open intellisense and the code should have selected "main" as a suggestion, but the listbox has failed to select the item.

the code that sets the selected item is:
IntellisenseViewModel line: 389

**Comment by grokys** [comment]
I believe this was a problem in AvalonStudio.
