### ISSUE TITLE
TextBox HorizontalScrollBar not displayed properly when setting AcceptsReturn to true

### ISSUE THREAD

**Issue by wieslawsoltes** [Perspex/Perspex#475]
```XAML
        <Style Selector="TextBox.xaml">
            <Setter Property="AcceptsReturn" Value="True"/>
            <Setter Property="TextWrapping" Value="NoWrap"/>
            <Setter Property="HorizontalScrollBarVisibility" Value="Auto"/>
            <Setter Property="VerticalScrollBarVisibility" Value="Auto"/>
        </Style>
```

```XAML
        <Style Selector="TextBox.xaml">
            <Setter Property="AcceptsReturn" Value="True"/>
            <Setter Property="TextWrapping" Value="NoWrap"/>
            <Setter Property="HorizontalScrollBarVisibility" Value="Visible"/>
            <Setter Property="VerticalScrollBarVisibility" Value="Auto"/>
        </Style>
```

**Comment by grokys** [comment]
The reason this isn't working is that the `TextBox.HorizontalScrollBarVisibility` property is currently a hack and should be treated as read-only. 

You should use the `ScrollBar.HorizontalScrollBarVisibility` attached property instead (as in WPF) and it should work according to my tests.

**Comment by wieslawsoltes** [comment]
@grokys The issue is still present when combining `AcceptsReturn=True` and `TextWrapping=NoWrap`

``` XAML
        <Style Selector="TextBox.xaml">
            <Setter Property="Padding" Value="4"/>
            <Setter Property="FontSize" Value="12"/>
            <Setter Property="Background" Value="{StyleResource BackgroundBrush}"/>
            <Setter Property="TextAlignment" Value="Left"/>
            <Setter Property="BorderBrush" Value="{StyleResource BorderBrush}"/>
            <Setter Property="BorderThickness" Value="1"/>
            <Setter Property="AcceptsReturn" Value="True"/>
            <Setter Property="TextWrapping" Value="NoWrap"/>
            <Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Auto"/>
            <Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto"/>
            <Setter Property="Foreground" Value="{StyleResource ForegroundBrush}"/>
        </Style>
```

Looks like here: https://github.com/Perspex/Perspex/blob/165702c73e3468a78330e080180d6e504d9c7112/src/Perspex.Controls/Presenters/TextPresenter.cs#L41 
is some unused variable `_canScrollHorizontally` related to the `TextWrappingProperty`.

**Comment by grokys** [comment]
Hmm, setting `ScrollViewer.HorizontalScrollBarVisibility="Visible"` on a multiline text box produces this for me:

![image](https://cloud.githubusercontent.com/assets/1775141/14002773/4f922c34-f14e-11e5-8036-f9dfd2dee95c.png)

However it doesn't seem to be respecting the `TextWrapping` property - is that your problem?

**Comment by wieslawsoltes** [comment]
Yes I have same issue:
![2016-03-23_23-28-21](https://cloud.githubusercontent.com/assets/2297442/14002852/faba0370-f14e-11e5-8460-2143d340fc6b.png)
using 

``` XAML
<Setter Property="AcceptsReturn" Value="True"/>
<Setter Property="TextWrapping" Value="NoWrap"/>
<Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Visible"/>
<Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto"/>
```

and
![2016-03-23_23-29-32](https://cloud.githubusercontent.com/assets/2297442/14002879/1d88b89c-f14f-11e5-8a80-0b01d14bf706.png)
using

``` XAML
<Setter Property="AcceptsReturn" Value="True"/>
<Setter Property="TextWrapping" Value="NoWrap"/>
<Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Auto"/>
<Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto"/>
```

**Comment by wieslawsoltes** [comment]
And this is look I expected:
![2016-03-23_23-32-45](https://cloud.githubusercontent.com/assets/2297442/14002955/9cfb0e5e-f14f-11e5-9a3c-f09f696655de.png)
but do get this I have to set `AcceptsReturn` to `False`.

``` XAML
<Setter Property="AcceptsReturn" Value="False"/>
<Setter Property="TextWrapping" Value="NoWrap"/>
<Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Auto"/>
<Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto"/>
```

**Comment by grokys** [comment]
Looking into it, it seems to be a problem with the layout system...

**Comment by grokys** [comment]
Ok, think I've fixed it this time.
