### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by raffaeler** [Perspex/Perspex#477]
I would strongly suggest to regenerate the http://perspex.github.io/ documentation removing the Microsoft copyright that would induce people to believe this is a Microsoft-owned project.

**Comment by grokys** [comment]
Good point - I didn't notice that!

**Comment by grokys** [comment]
@wieslawsoltes any idea how to do this? I had a quick look but couldn't see any documentation on how to change this.

**Comment by wieslawsoltes** [comment]
@grokys No simple solution exist. There is no variable you can change for this. My guess is you have use custom template by copying for example the default from docfx and changing footer.

Example I have found:
https://github.com/sethjuarez/numl/blob/dev/Docs/docfx.json#L54
https://github.com/sethjuarez/numl/blob/dev/Docs/template/partials/footer.tmpl.partial
https://github.com/sethjuarez/numl/tree/dev/Docs
https://github.com/dotnet/docfx/tree/dev/src/docfx/Template

**Comment by wieslawsoltes** [comment]
@grokys Ok I have found solution, will submit PR

For copyright can I use `The Perspex Project` or something else ?
