### ISSUE TITLE
Native window control

### ISSUE THREAD

**Issue by KeKl** [Perspex/Perspex#490]
Hi there,

currently I try to embed a native window into a perspex Control.
The repo is under https://github.com/KeKl/PerspexNativeWindow

I asked already in the git room. I can add the Control in Code behind of window
with: 
`this.VisualChildren.Add(new NativeControl(this.PlatformImpl.Handle));
`

But in the ctor without args in NativeWindowHost.cs I cannot get the window handle of the root
window.

So how do I get the platform handle?

Thanks.

**Comment by Seeker1437** [comment]
From my understanding, you want to get the window then do, (assuming `window` is an instance of the host Window, `window.PlatformImpl.Handle.Handle

**Comment by Seeker1437** [comment]
so basically you need this.VisualChildren.Add(new NativeControl(this.PlatformImpl.Handle.Handle));

**Comment by KeKl** [comment]
Thank you, but

1. I dont have an instance of the window in a children control. Thats what I need.
2. Thats exactly what I have. 

I dont want Code behind, I want to use xaml.

```
protected NativeWindowHost()
{
    //var p =  this.Parent;

    //var vr = this.GetVisualParent();
			
    //var tl = (TopLevel)vr;
			
     //BuildWindow(tl.PlatformImpl.Handle);
}
```
In the constructor of a child Control I want to get the window in which the Control is hosted, no DI.

**Comment by KeKl** [comment]
:-) you were a few seconds faster.

**Comment by grokys** [comment]
Maybe you could explain why you think it looks a little bad?

**Comment by KeKl** [comment]
Because I can work with the window the first time, when the window was build. I added an event Built...

**Comment by grokys** [comment]
Sorry, I don't understand...

**Comment by Seeker1437** [comment]
What he means is that he can or tries to do things with the window before its attached to either tree.

**Comment by grokys** [comment]
Before a control is attached to a visual tree, it doesn't know what its containing `Window` is going to be, so there can be no HWND.

**Comment by danwalmsley** [comment]
I don't see anything wrong with OnAttachedToVisualTree, that's the point where the window handle is guaranteed to be created.

**Comment by KeKl** [comment]
Thanks, I´v got an OpenGL triangle to screen. Currently I try to solve the resize problem.
What I do is to track the bounds of the control relative to the visual root and then update the native
window. But I have some issues with that... I have to try some things...
