### ISSUE TITLE
ItemsControl prevents view models from being GCed

### ISSUE THREAD

**Issue by danwalmsley** [Perspex/Perspex#520]
Here is a minimal repro in the Perspex test app.

use this commit:
https://github.com/VitalElement/Perspex/commit/ab3237a92310f6d438a8bcacc77800698ac5171d

then run the app and click on the Xaml test app and click on the last tab.

![image](https://cloud.githubusercontent.com/assets/4672627/14655884/64cdb116-067c-11e6-8129-8775d23e7f1e.png)

Then close the tabs, by clicking X, you will find nothing gets GCed until the application is closed.

**Comment by donandren** [comment]
Some unit tests are available to represent the problem
at https://github.com/donandren/Perspex/tree/ItemsControlsLeaks

**Comment by danwalmsley** [comment]
This was  fixed by #519

**Comment by grokys** [comment]
Hold on I'm confused - @donandren are these problems fixed?

**Comment by donandren** [comment]
@grokys It doesn't sound like the problems are fixed, may be only some aspect of it, but in the unit tests is clear that the problem is still not solved

**Comment by donandren** [comment]
@grokys  mine fault sorry, I've fixed the unit tests in https://github.com/donandren/Perspex/tree/ItemsControlsLeaks and now they are passed ok.
