### ISSUE TITLE
Not DPI aware on Windows

### ISSUE THREAD

**Issue by Robertofon** [Perspex/Perspex#70]
I am using a 4k Monitor with dpi around 132 and the example program looks uncool, since it is scaled up.
I had a succesful try to make User32 know Perspex is DPI aware and I get it to display 1:1 (unscaled). Of course quite smallish, then.
My Idea now is to change the Window and Popup-Style to have the RenderTransform  > 1.0
But how shall this be communicated through the layers. Maybe just inside the Win32Platform as a static used when Windows are opened (they also have to be larger). But the themes are elsewhere.

So what is the consensus about a global ScaleFactor-DP for the Themes?

**Comment by grokys** [comment]
Hi Robertofan - thanks, yes I know this is something that needs addressing. I'm not sure of the correct way to go about it - I don't like the idea of using a RenderTransform as RenderTransforms may be altered by the user in things like animations. 

I think the scaling probably should be handled by the rendering subsystem, I know that Direct2D supports it: https://msdn.microsoft.com/en-us/library/windows/desktop/dd756649(v=vs.85).aspx

**Comment by Robertofon** [comment]
Hi Steven. I agree... the point to screw around should actually be one layer above the mentioned RenderTransfrom. So you mean actually the rendering subsytem should change it's coordinate system to be just by a factor wider. I think this is also what WPF does.
I can have a try implementing this using the example program on windows. 
I managed to influence the win32 part but that made me realize it is not using directx. How would I activate direct2D rendering?
And point me into some direction code wise?

BTW: MS allows Per monitor DPI settings since Win8 - Apps are meant to change their window size on the "drag". The window system does notify a window when it thinks most parts are on a certain monitor. Parts on other monitors are scaled appropriately. I think this should be the 2nd goal.

**Comment by grokys** [comment]
Yes, I think you have the right idea. I think it should be possible to do automatically in Direct2D: https://msdn.microsoft.com/en-us/library/windows/desktop/dd756693(v=vs.85).aspx

**Comment by Robertofon** [comment]
I investigated an tried some code. (well it's already weeks ago). Everything is scaled on the same location (ugly). But I want to invest some more time - however again not today. But let me say: This is one of the most interesting CLR projects these days.

**Comment by kekekeks** [comment]
I don't see `user32.dll!SetProcessDPIAware` called anywhere in the code base, that's probably the issue.

**Comment by Robertofon** [comment]
That is only in my local repository. It does it's job - The app is shown smaller eg 1:1 which is usually too small. So I tried to scale up the creation but I am missing a point.
Do you currently do anything to DPI awareness (I got the feeling from comments) or can I still try to solve it... yeh I did not do a lot recently

**Comment by ncarrillo** [comment]
This is what is required on Windows:

- [ ] SetProcessDPIAware needs to be called _before_ any Windows are created. You can probably use `Win32Platform` as the place to do it.
- [ ] You need to get the DPI. Direct2D provides an API for it, but it should also be possible via Win32. This way you avoid having a reference to Direct2D in the Win32 project.
- [ ] Window sizing needs to be scaled according to the DPI.
- [ ] Some window messages (WM_MOUSEMOVE for example) are sent using physical sizes, so they'll need to be scaled by the screen DPI.

Rendering should *just work* once you set the process as DPI aware because Direct2D scales using device-independent pixels. The scaling basically comes for free.

[Here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd756649(v=vs.85).aspx) is a link to more information on High DPI and Direct2D.

**Comment by grokys** [comment]
#387 provided the code for enabling DPI awareness, but our layout system's `UseLayoutRounding` implementation would need to be taught to be DPI aware too before we have a full solution to this:

https://github.com/Perspex/Perspex/blob/master/src/Perspex.Layout/Layoutable.cs#L502
https://github.com/Perspex/Perspex/blob/master/src/Perspex.Layout/Layoutable.cs#L542
https://github.com/Perspex/Perspex/blob/master/src/Perspex.Layout/Layoutable.cs#L576

**Comment by grokys** [comment]
There is an implementation of DPI awareness on the `dpi-aware` branch.

**Comment by grokys** [comment]
`dpi-aware` has been merged to master, though it may still have problems as I'm not sure how much it's been tested.

It will also have broken the mobile ports, as I've not changed them to use the new scaling system and they will always have a scaling of 1.
