### ISSUE TITLE
Test on Linux

### ISSUE THREAD

**Issue by grokys** [Perspex/Perspex#78]
Make sure that Perspex is running OK on Linux and write some docs explaining how to get up-and-running if there are any non-straightforward parts.

**Comment by grokys** [comment]
Tested on Linux using mono 3.0.2 and getting weird failures. Try again with the next release I guess.

**Comment by grokys** [comment]
Now kinda working on mono 4.2 alpha. Some issues remain:

- [ ] There are a few compiler errors on the tests. Reported bug: https://bugzilla.xamarin.com/show_bug.cgi?id=33487
- [ ] ReactiveUI causes a runtime assertion. Reported bug: https://bugzilla.xamarin.com/show_bug.cgi?id=33488
- [ ] Even if that assertion wasn't being thrown, ReactiveUI tries to initialize WPF which doesn't exist on Linux. Discussion: https://github.com/reactiveui/ReactiveUI/issues/925
- [ ] OmniXaml currently requires framework version 4.6 which isn't available on mono. @SuperJMN is going to lower it to 4.5.1.

Removing ReactiveUI from TestApplication allows it to run though, so partial sucess.

**Comment by kekekeks** [comment]
With ReactiveUI being built as part of Perspex it leaves us with https://github.com/Perspex/Perspex/issues/85 and https://github.com/Perspex/Perspex/issues/86
