### ISSUE TITLE
Allow Styles to be defined using XAML

### ISSUE THREAD

**Issue by SuperJMN** [Perspex/Perspex#91]

**Comment by grokys** [comment]
I think this will require:

- [ ] A parser for selectors, i..e `Button.class`
- [ ] A converter for `PerspexProperty`s

Assuming the second doesn't yet exist, @SuperJMN ?

**Comment by SuperJMN** [comment]
I'm not sure. How can Styles be defined in XAML? How could they look like?
They would require conversion only if they will be ty defined as a plain string.

Also, I are styles composed of setters only? I'll edit this comment later to make it more formal.

**Comment by grokys** [comment]
I'm thinking they would look something like this:

    <Style Selector="Button.foo">
        <Setter Property="Background" Value="Red"/>
    </Style>

**Comment by SuperJMN** [comment]
OK, I start to see . What you are showing is XAML per se and OmniXAML supports that already. What's more interesting is the implementation details and the conversions that are supposed to take place.

 - Is "Button.foo" usabe without conversion? I mean, do Style already handle it as string?
 - The same for "Button.Background"

Also, I would want to know if Styles are like in standard XAML in terms of ownership. I mean, there is a property Button.Style, if you want to explicitly set the style of a Button and there is a Button.Resources in which you can add styles to be used by its children.

Also, Styles should be "attachable" dynamically, after the owner has been created.

If Styles are not parameterless, we should then create a wrapper for XAML, like I did with DataTemplates. One is the pure pristine framework object, and the other is the bridge that makes it possible to use it the way XAML like to work.

Needless to say that, it would be ideal if Styles have an interface, because the bridge object could just implement it if we have the need.

**Comment by grokys** [comment]
Regarding your two questions, they are exactly the two points in my original comment ;)

A control has a `Styles` collection where styles can be added. All classes involved are default-constructable so should be creatable via xaml.

**Comment by grokys** [comment]
Added f6e1e658dd50d10dd1504d631794a139cc7cca6b
